In [5]:
import pandas as pd

In [6]:
pd.__file__

'/home/chidex/DE/data-engineering/pipeline/.venv/lib/python3.13/site-packages/pandas/__init__.py'

In [7]:
prefix = 'https://github.com/DataTalksClub/nyc-tlc-data/releases/download/misc/'
url = f'{prefix}/taxi_zone_lookup.csv'

In [8]:
df = pd.read_csv(url)

In [9]:
df

     LocationID        Borough                     Zone service_zone
0             1            EWR           Newark Airport          EWR
1             2         Queens              Jamaica Bay    Boro Zone
2             3          Bronx  Allerton/Pelham Gardens    Boro Zone
3             4      Manhattan            Alphabet City  Yellow Zone
4             5  Staten Island            Arden Heights    Boro Zone
..          ...            ...                      ...          ...
260         261      Manhattan       World Trade Center  Yellow Zone
261         262      Manhattan           Yorkville East  Yellow Zone
262         263      Manhattan           Yorkville West  Yellow Zone
263         264        Unknown                       NV          NaN
264         265        Unknown                      NaN          NaN

[265 rows x 4 columns]

In [10]:
df.shape

(265, 4)

In [179]:
len(df)

1369765

In [180]:
df.()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1.0,2021-01-01 00:30:10,2021-01-01 00:36:12,1.0,2.10,1.0,N,142,43,2.0,8.0,3.0,0.5,0.00,0.0,0.3,11.80,2.5
1,1.0,2021-01-01 00:51:20,2021-01-01 00:52:19,1.0,0.20,1.0,N,238,151,2.0,3.0,0.5,0.5,0.00,0.0,0.3,4.30,0.0
2,1.0,2021-01-01 00:43:30,2021-01-01 01:11:06,1.0,14.70,1.0,N,132,165,1.0,42.0,0.5,0.5,8.65,0.0,0.3,51.95,0.0
3,1.0,2021-01-01 00:15:48,2021-01-01 00:31:01,0.0,10.60,1.0,N,138,132,1.0,29.0,0.5,0.5,6.05,0.0,0.3,36.35,0.0
4,2.0,2021-01-01 00:31:49,2021-01-01 00:48:21,1.0,4.94,1.0,N,68,33,1.0,16.5,0.5,0.5,4.06,0.0,0.3,24.36,2.5

In [1]:
dtype = {
    "LocationID": "int64",
    "Borough": "string",
    "Zone": "string",
    "service_zone": "string"
}

df = pd.read_csv(
    url,
    dtype=dtype
)

NameError: name 'pd' is not defined

In [182]:
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1,2021-01-01 00:30:10,2021-01-01 00:36:12,1,2.10,1,N,142,43,2,8.0,3.0,0.5,0.00,0.0,0.3,11.80,2.5
1,1,2021-01-01 00:51:20,2021-01-01 00:52:19,1,0.20,1,N,238,151,2,3.0,0.5,0.5,0.00,0.0,0.3,4.30,0.0
2,1,2021-01-01 00:43:30,2021-01-01 01:11:06,1,14.70,1,N,132,165,1,42.0,0.5,0.5,8.65,0.0,0.3,51.95,0.0
3,1,2021-01-01 00:15:48,2021-01-01 00:31:01,0,10.60,1,N,138,132,1,29.0,0.5,0.5,6.05,0.0,0.3,36.35,0.0
4,2,2021-01-01 00:31:49,2021-01-01 00:48:21,1,4.94,1,N,68,33,1,16.5,0.5,0.5,4.06,0.0,0.3,24.36,2.5

In [183]:
df['tpep_pickup_datetime']

0         2021-01-01 00:30:10
1         2021-01-01 00:51:20
2         2021-01-01 00:43:30
3         2021-01-01 00:15:48
4         2021-01-01 00:31:49
                  ...
1369760   2021-01-25 08:32:04
1369761   2021-01-25 08:34:00
1369762   2021-01-25 08:37:00
1369763   2021-01-25 08:28:00
1369764   2021-01-25 08:38:00
Name: tpep_pickup_datetime, Length: 1369765, dtype: datetime64[ns]

In [184]:
df.shape

(1369765, 18)

In [153]:
import sys
!uv pip install -v sqlalchemy

DEBUG uv 0.9.21 (0dc9556ad 2025-12-30)
DEBUG Acquired shared lock for `/home/chidex/.cache/uv`
DEBUG Searching for default Python interpreter in virtual environments
DEBUG Found `cpython-3.13.11-linux-x86_64-gnu` at `/home/chidex/DE/data-engineering/pipeline/.venv/bin/python3` (active virtual environment)
DEBUG Using Python 3.13.11 environment at: .venv
DEBUG Acquired exclusive lock for `.venv`
DEBUG Requirement satisfied: greenlet>=1 ; platform_machine == 'AMD64' or platform_machine == 'WIN32' or platform_machine == 'aarch64' or platform_machine == 'amd64' or platform_machine == 'ppc64le' or platform_machine == 'win32' or platform_machine == 'x86_64'
DEBUG Requirement satisfied: sqlalchemy
DEBUG Requirement satisfied: typing-extensions>=4.6.0
Audited 1 package in 27ms
DEBUG Released lock at `/home/chidex/DE/data-engineering/pipeline/.venv/.lock`
DEBUG Released lock at `/home/chidex/.cache/uv/.lock`

In [154]:
!pwd
!ls -ld .

#Run this in a terminal (NOT Jupyter):
#sudo chown -R chidex:chidex /home/chidex/DE/data-engineering/pipeline

/home/chidex/DE/data-engineering/pipeline
drwxr-xr-x 5 chidex chidex 4096 Jan 19 11:54 .

In [155]:
import sys
!uv add sqlalchemy

Resolved 120 packages in 0.72ms
Audited 13 packages in 0.19ms

In [186]:
!uv pip install -v notebook

DEBUG uv 0.9.21 (0dc9556ad 2025-12-30)
DEBUG Acquired shared lock for `/home/chidex/.cache/uv`
DEBUG Searching for default Python interpreter in virtual environments
DEBUG Found `cpython-3.13.11-linux-x86_64-gnu` at `/home/chidex/DE/data-engineering/pipeline/.venv/bin/python3` (active virtual environment)
DEBUG Using Python 3.13.11 environment at: .venv
DEBUG Acquired exclusive lock for `.venv`
DEBUG Requirement satisfied: anyio
DEBUG Requirement satisfied: anyio>=3.1.0
DEBUG Requirement satisfied: argon2-cffi-bindings
DEBUG Requirement satisfied: argon2-cffi>=21.1
DEBUG Requirement satisfied: arrow>=0.15.0
DEBUG Requirement satisfied: asttokens>=2.1.0
DEBUG Requirement satisfied: async-lru>=1.0.0
DEBUG Requirement satisfied: attrs>=22.2.0
DEBUG Requirement satisfied: babel>=2.10
DEBUG Requirement satisfied: beautifulsoup4
DEBUG Requirement satisfied: bleach[css]!=5.0.0
DEBUG Requirement satisfied: certifi
DEBUG Requirement satisfied: certifi>=2017.4.17
DEBUG Requirement satisfied: cffi>=1.0.1 ; python_full_version < '3.14'
DEBUG Requirement satisfied: charset-normalizer>=2, <4
DEBUG Requirement satisfied: comm>=0.1.1
DEBUG Requirement satisfied: debugpy>=1.6.5
DEBUG Requirement satisfied: decorator>=4.3.2
DEBUG Requirement satisfied: defusedxml
DEBUG Requirement satisfied: executing>=1.2.0
DEBUG Requirement satisfied: fastjsonschema>=2.15
DEBUG Requirement satisfied: fqdn ; extra == 'format-nongpl'
DEBUG Requirement satisfied: h11>=0.16
DEBUG Requirement satisfied: httpcore==1.*
DEBUG Requirement satisfied: httpx>=0.25.0, <1
DEBUG Requirement satisfied: idna
DEBUG Requirement satisfied: idna ; extra == 'format-nongpl'
DEBUG Requirement satisfied: idna>=2.5, <4
DEBUG Requirement satisfied: idna>=2.8
DEBUG Requirement satisfied: ipykernel>=6.5.0, !=6.30.0
DEBUG Requirement satisfied: ipython-pygments-lexers>=1.0.0
DEBUG Requirement satisfied: ipython>=7.23.1
DEBUG Requirement satisfied: isoduration ; extra == 'format-nongpl'
DEBUG Requirement satisfied: jedi>=0.18.1
DEBUG Requirement satisfied: jinja2>=3.0
DEBUG Requirement satisfied: jinja2>=3.0.3
DEBUG Requirement satisfied: json5>=0.9.0
DEBUG Requirement satisfied: jsonpointer>1.13 ; extra == 'format-nongpl'
DEBUG Requirement satisfied: jsonschema-specifications>=2023.3.6
DEBUG Requirement satisfied: jsonschema>=2.6
DEBUG Requirement satisfied: jsonschema>=4.18.0
DEBUG Requirement satisfied: jsonschema[format-nongpl]>=4.18.0
DEBUG Requirement satisfied: jupyter-client>=6.1.12
DEBUG Requirement satisfied: jupyter-client>=7.4.4
DEBUG Requirement satisfied: jupyter-client>=8.0.0
DEBUG Requirement satisfied: jupyter-core
DEBUG Requirement satisfied: jupyter-core>=4.12, !=5.0.*
DEBUG Requirement satisfied: jupyter-core>=4.7
DEBUG Requirement satisfied: jupyter-core>=5.1
DEBUG Requirement satisfied: jupyter-events>=0.11.0
DEBUG Requirement satisfied: jupyter-lsp>=2.0.0
DEBUG Requirement satisfied: jupyter-server-terminals>=0.4.4
DEBUG Requirement satisfied: jupyter-server>=1.1.2
DEBUG Requirement satisfied: jupyter-server>=1.21, <3
DEBUG Requirement satisfied: jupyter-server>=1.8, <3
DEBUG Requirement satisfied: jupyter-server>=2.4.0, <3
DEBUG Requirement satisfied: jupyterlab-pygments
DEBUG Requirement satisfied: jupyterlab-server>=2.28.0, <3
DEBUG Requirement satisfied: jupyterlab>=4.5.2, <4.6
DEBUG Requirement satisfied: lark>=1.2.2
DEBUG Requirement satisfied: markupsafe>=2.0
DEBUG Requirement satisfied: matplotlib-inline>=0.1
DEBUG Requirement satisfied: matplotlib-inline>=0.1.5
DEBUG Requirement satisfied: mistune>=2.0.3, <4
DEBUG Requirement satisfied: nbclient>=0.5.0
DEBUG Requirement satisfied: nbconvert>=6.4.4
DEBUG Requirement satisfied: nbformat>=5.1.3
DEBUG Requirement satisfied: nbformat>=5.3.0
DEBUG Requirement satisfied: nbformat>=5.7
DEBUG Requirement satisfied: nest-asyncio>=1.4
DEBUG Requirement satisfied: notebook
DEBUG Requirement satisfied: notebook-shim>=0.2
DEBUG Requirement satisfied: notebook-shim>=0.2, <0.3
DEBUG Requirement satisfied: packaging
DEBUG Requirement satisfied: packaging>=21.3
DEBUG Requirement satisfied: packaging>=22.0
DEBUG Requirement satisfied: pandocfilters>=1.4.1
DEBUG Requirement satisfied: parso>=0.8.4, <0.9.0
DEBUG Requirement satisfied: pexpect>4.3 ; sys_platform != 'emscripten' and sys_platform != 'win32'
DEBUG Requirement satisfied: platformdirs>=2.5
DEBUG Requirement satisfied: prometheus-client>=0.9
DEBUG Requirement satisfied: prompt-toolkit>=3.0.41, <3.1.0
DEBUG Requirement satisfied: psutil>=5.7
DEBUG Requirement satisfied: ptyprocess ; os_name != 'nt'
DEBUG Requirement satisfied: ptyprocess>=0.5
DEBUG Requirement satisfied: pure-eval
DEBUG Requirement satisfied: pycparser ; implementation_name != 'PyPy'
DEBUG Requirement satisfied: pygments
DEBUG Requirement satisfied: pygments>=2.11.0
DEBUG Requirement satisfied: pygments>=2.4.1
DEBUG Requirement satisfied: python-dateutil>=2.7.0
DEBUG Requirement satisfied: python-dateutil>=2.8.2
DEBUG Requirement satisfied: python-json-logger>=2.0.4
DEBUG Requirement satisfied: pyyaml>=5.3
DEBUG Requirement satisfied: pyzmq>=24
DEBUG Requirement satisfied: pyzmq>=25.0
DEBUG Requirement satisfied: referencing
DEBUG Requirement satisfied: referencing>=0.28.4
DEBUG Requirement satisfied: referencing>=0.31.0
DEBUG Requirement satisfied: requests>=2.31
DEBUG Requirement satisfied: rfc3339-validator
DEBUG Requirement satisfied: rfc3339-validator ; extra == 'format-nongpl'
DEBUG Requirement satisfied: rfc3986-validator>0.1.0 ; extra == 'format-nongpl'
DEBUG Requirement satisfied: rfc3986-validator>=0.1.1
DEBUG Requirement satisfied: rfc3987-syntax>=1.1.0 ; extra == 'format-nongpl'
DEBUG Requirement satisfied: rpds-py>=0.25.0
DEBUG Requirement satisfied: rpds-py>=0.7.0
DEBUG Requirement satisfied: send2trash>=1.8.2
DEBUG Requirement satisfied: setuptools>=41.1.0
DEBUG Requirement satisfied: six
DEBUG Requirement satisfied: six>=1.5
DEBUG Requirement satisfied: soupsieve>=1.6.1
DEBUG Requirement satisfied: stack-data>=0.6.0
DEBUG Requirement satisfied: terminado>=0.8.3
DEBUG Requirement satisfied: tinycss2>=1.1.0, <1.5 ; extra == 'css'
DEBUG Requirement satisfied: tornado>=6.1.0
DEBUG Requirement satisfied: tornado>=6.2.0
DEBUG Requirement satisfied: tornado>=6.4.1
DEBUG Requirement satisfied: traitlets
DEBUG Requirement satisfied: traitlets>=5.1
DEBUG Requirement satisfied: traitlets>=5.13.0
DEBUG Requirement satisfied: traitlets>=5.3
DEBUG Requirement satisfied: traitlets>=5.4
DEBUG Requirement satisfied: traitlets>=5.6.0
DEBUG Requirement satisfied: typing-extensions>=4.0.0
DEBUG Requirement satisfied: tzdata ; python_full_version >= '3.9'
DEBUG Requirement satisfied: uri-template ; extra == 'format-nongpl'
DEBUG Requirement satisfied: urllib3>=1.21.1, <3
DEBUG Requirement satisfied: wcwidth
DEBUG Requirement satisfied: webcolors>=24.6.0 ; extra == 'format-nongpl'
DEBUG Requirement satisfied: webencodings
DEBUG Requirement satisfied: webencodings>=0.4
DEBUG Requirement satisfied: websocket-client>=1.7
Audited 1 package in 31ms
DEBUG Released lock at `/home/chidex/DE/data-engineering/pipeline/.venv/.lock`
DEBUG Released lock at `/home/chidex/.cache/uv/.lock`

In [156]:
!uv --version

uv 0.9.21 (0dc9556ad 2025-12-30)

In [157]:
from sqlalchemy import create_engine
engine = create_engine('postgresql://root:root@localhost:5432/ny_taxi')

In [158]:
!uv add psycopg2-binary

Resolved 120 packages in 0.69ms
Audited 13 packages in 0.16ms

In [159]:
from sqlalchemy import create_engine
engine = create_engine('postgresql://root:root@localhost:5432/ny_taxi')

In [160]:
df

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1,2021-01-01 00:30:10,2021-01-01 00:36:12,1,2.10,1,N,142,43,2,8.00,3.00,0.5,0.00,0.0,0.3,11.80,2.5
1,1,2021-01-01 00:51:20,2021-01-01 00:52:19,1,0.20,1,N,238,151,2,3.00,0.50,0.5,0.00,0.0,0.3,4.30,0.0
2,1,2021-01-01 00:43:30,2021-01-01 01:11:06,1,14.70,1,N,132,165,1,42.00,0.50,0.5,8.65,0.0,0.3,51.95,0.0
3,1,2021-01-01 00:15:48,2021-01-01 00:31:01,0,10.60,1,N,138,132,1,29.00,0.50,0.5,6.05,0.0,0.3,36.35,0.0
4,2,2021-01-01 00:31:49,2021-01-01 00:48:21,1,4.94,1,N,68,33,1,16.50,0.50,0.5,4.06,0.0,0.3,24.36,2.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1369760,<NA>,2021-01-25 08:32:04,2021-01-25 08:49:32,<NA>,8.80,<NA>,<NA>,135,82,<NA>,21.84,2.75,0.5,0.00,0.0,0.3,25.39,0.0
1369761,<NA>,2021-01-25 08:34:00,2021-01-25 09:04:00,<NA>,5.86,<NA>,<NA>,42,161,<NA>,26.67,2.75,0.5,0.00,0.0,0.3,30.22,0.0
1369762,<NA>,2021-01-25 08:37:00,2021-01-25 08:53:00,<NA>,4.45,<NA>,<NA>,14,106,<NA>,25.29,2.75,0.5,0.00,0.0,0.3,28.84,0.0
1369763,<NA>,2021-01-25 08:28:00,2021-01-25 08:50:00,<NA>,10.04,<NA>,<NA>,175,216,<NA>,28.24,2.75,0.5,0.00,0.0,0.3,31.79,0.0
1369764,<NA>,2021-01-25 08:38:00,2021-01-25 08:50:00,<NA>,4.93,<NA>,<NA>,248,168,<NA>,20.76,2.75,0.5,0.00,0.0,0.3,24.31,0.0

In [161]:
print(pd.io.sql.get_schema(df, name='yellow_taxi_data', con=engine))

CREATE TABLE yellow_taxi_data (
	"VendorID" BIGINT,
	tpep_pickup_datetime TIMESTAMP WITHOUT TIME ZONE,
	tpep_dropoff_datetime TIMESTAMP WITHOUT TIME ZONE,
	passenger_count BIGINT,
	trip_distance FLOAT(53),
	"RatecodeID" BIGINT,
	store_and_fwd_flag TEXT,
	"PULocationID" BIGINT,
	"DOLocationID" BIGINT,
	payment_type BIGINT,
	fare_amount FLOAT(53),
	extra FLOAT(53),
	mta_tax FLOAT(53),
	tip_amount FLOAT(53),
	tolls_amount FLOAT(53),
	improvement_surcharge FLOAT(53),
	total_amount FLOAT(53),
	congestion_surcharge FLOAT(53)
)

In [162]:
df.head(n=0).to_sql(name='yellow_taxi_data', con=engine, if_exists='replace')

0

In [163]:
len(df)

1369765

In [194]:
df_iter = pd.read_csv(
    url,
    dtype=dtype,
    parse_dates=parse_dates,
    iterator=True,
    chunksize=100000,
)

In [195]:
df_iter

In [166]:
for df in df_iter:
    print(len(df))

100000
100000
100000
100000
100000
100000
100000
100000
100000
100000
100000
100000
100000
69765

In [91]:
#for df in df_iter:
 #   df.head(n=0).to_sql(name='yellow_taxi_data', con=engine, if_exists='append')

Resolved 120 packages in 0.77ms
Audited 13 packages in 0.19ms
Audited 1 package in 6ms

In [134]:
!uv pip install tqdm
!uv add tqdm
!uv pip install ipywidgets

Audited 1 package in 1ms

In [187]:

from tqdm.auto import tqdm

In [196]:
for df_chunk in tqdm(df_iter):
    df_chunk.to_sql(name='yellow_taxi_data', con=engine, if_exists='append')

0it [00:00, ?it/s]

In [172]:
from tqdm.notebook import tqdm

for df_chunk in tqdm(df_iter, desc="Uploading chunks"):
    df_chunk.to_sql(name='yellow_taxi_data', con=engine, if_exists='append')

Uploading chunks: 0it [00:00, ?it/s]

In [171]:
!uv pip install --python "{sys.executable}" ipywidgets

Audited 1 package in 4ms

In [170]:
!uv pip install --python "{sys.executable}" notebook

Audited 1 package in 64ms

In [193]:
# Simple tqdm test
from tqdm.auto import tqdm
import time  # just to slow down for visibility

# Loop 10 iterations with a progress bar
for i in tqdm(range(10), desc="Testing tqdm", ncols=80):
    time.sleep(0.2)  # sleep 0.2 seconds so you can see the bar updating

print("✅ tqdm is working!")

Testing tqdm:   0%|                                      | 0/10 [00:00<?, ?it/s]

✅ tqdm is working!